[2020-04-11T16:22:05.530199+00:00] request.INFO: Matched route "purchaseList". {"route":"purchaseList","route_parameters":{"_route":"purchaseList","_controller":"App\\Controller\\PurchaseController::index"},"request_uri":"http://localhost/purchase/","method":"GET"} []
[2020-04-11T16:22:05.572268+00:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in driver: SQLSTATE[HY000] [1044] Access denied for user 'calculator'@'%' to database 'calculator_test'" at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 93 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [1044] Access denied for user 'calculator'@'%' to database 'calculator_test' at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:93)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDOException(code: 1044): SQLSTATE[HY000] [1044] Access denied for user 'calculator'@'%' to database 'calculator_test' at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31)\n[previous exception] [object] (PDOException(code: 1044): SQLSTATE[HY000] [1044] Access denied for user 'calculator'@'%' to database 'calculator_test' at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27)"} []
